# Generated by Django 3.1 on 2020-08-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.PositiveIntegerField(default=5, verbose_name='Semister'),
        ),
    ]
