# Generated by Django 3.1 on 2020-08-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200829_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='submitted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
