# Generated by Django 3.1 on 2020-08-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class', '__first__'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('exam_date', models.DateField(verbose_name='Submission Date')),
                ('question1', models.TextField(default='Add Question', null=True, verbose_name='Question 1')),
                ('question1_total_marks', models.PositiveIntegerField(null=True)),
                ('question2', models.TextField(default='Add Question', null=True, verbose_name='Question 2')),
                ('question2_total_marks', models.PositiveIntegerField(null=True)),
                ('question3', models.TextField(default='Add Question', null=True, verbose_name='Question 3')),
                ('question3_total_marks', models.PositiveIntegerField(null=True)),
                ('full_marks', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1_answer', models.TextField(default='Add Question', null=True, verbose_name='Question 1 Answer')),
                ('question1_marks', models.PositiveIntegerField(null=True)),
                ('question2_answer', models.TextField(default='Add Question', null=True, verbose_name='Question 2 Answer')),
                ('question2_marks', models.PositiveIntegerField(null=True)),
                ('question3_answer', models.TextField(default='Add Question', null=True, verbose_name='Question 3 Answer')),
                ('question3_marks', models.PositiveIntegerField(null=True)),
                ('total_marks_obtained', models.PositiveIntegerField(null=True)),
                ('examQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer', to='assignment.student')),
            ],
        ),
    ]
