# Generated by Django 3.1 on 2020-08-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examquestions_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestions',
            name='subject',
        ),
    ]
