# Generated by Django 3.1 on 2020-08-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0003_remove_examquestions_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
