# Generated by Django 3.1 on 2020-08-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='Name of Subject')),
                ('sem', models.PositiveIntegerField(verbose_name='Semister')),
                ('course_time', models.PositiveIntegerField(verbose_name='Total study Hour')),
                ('class_link', models.CharField(max_length=100, verbose_name='Link for online class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Name of Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(verbose_name='Day of week in integer')),
                ('start_time', models.TimeField(verbose_name='Class start time')),
                ('end_time', models.TimeField(verbose_name='Class end time')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.class', verbose_name='Subject Name')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.teacher', verbose_name='Name of Teacher'),
        ),
    ]
