# Generated by Django 3.1 on 2020-08-28 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_link',
        ),
        migrations.AddField(
            model_name='routine',
            name='class_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Link for online class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name of Teacher'),
        ),
    ]
