# Generated by Django 3.1 on 2020-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.TextField(max_length=100, verbose_name='Name of Subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_name',
            field=models.TextField(max_length=100, verbose_name='Name of Teacher'),
        ),
    ]
