# Generated by Django 3.1 on 2020-08-29 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0002_auto_20200828_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name of Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.teacher', verbose_name='Name of Teacher'),
        ),
    ]
