# Generated by Django 3.1 on 2020-08-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faceDetector.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacesTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
