# Generated by Django 3.1 on 2020-08-28 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faceDetector.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacesTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFacesTraining.user_directory_path, verbose_name='Image5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFaceRecognize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=faceDetector.models.UserFaceRecognize.user_directory_path, verbose_name='Image1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('examQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_present', models.BooleanField(default=False)),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
